name: QLCTApp
options:
  bundleIdPrefix: com.khanhnm

configs:
  Debug: debug
  Release: release

settings:
  SWIFT_VERSION: 5.9

targets:
  QLCTApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    bundleId: com.khanhnm.qlct
    dependencies:
      - target: QLCTShare
        embed: true
        codeSign: true
    sources:
      - path: .
        excludes:
          - ShareExtension
          - Tests
          - build
    settings:
      INFOPLIST_FILE: AppInfo.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.khanhnm.QLCTApp
      CODE_SIGN_ENTITLEMENTS: QLCTApp.entitlements

  QLCTShare:
    type: app-extension
    platform: iOS
    deploymentTarget: "16.0"
    bundleId: com.khanhnm.qlct.share
    sources:
      - path: ShareExtension
      - path: SharedConstants.swift
    settings:
      INFOPLIST_FILE: ShareExtension/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.khanhnm.QLCTApp.share
      CODE_SIGN_ENTITLEMENTS: ShareExtension/QLCTShare.entitlements
      APPLICATION_EXTENSION_API_ONLY: true

  QLCTAppTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Tests
    dependencies:
      - target: QLCTApp
    settings:
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/QLCTApp.app/QLCTApp"
      BUNDLE_LOADER: "$(TEST_HOST)"
